---
version: "3.5"
services:

  # Pihole for ad blocking
  pihole:
    image: pihole/pihole
    environment:
      TZ: 'Europe/Belgrade'
      WEBPASSWORD: fU1HRlMxGy9oNlkPxYSc
    volumes:
      - ./data/pihole/etc/pihole:/etc/pihole
      - ./data/pihole/etc/dnsmasq:/etc/dnsmasq
    restart: unless-stopped
    networks:
      - home

    networks:
      home:
        ipv4_address: 10.5.0.2

    labels:
      - "traefik.enable=true"

      - "traefik.http.services.pihole.loadbalancer.server.port=80"

      - "traefik.http.middlewares.pihole-prefix.addprefix.prefix=/admin"

      - "traefik.http.routers.pihole.service=pihole"
      - "traefik.http.routers.pihole.rule=Host(`pihole.local`)"
      - "traefik.http.routers.pihole.middlewares=pihole-prefix"

  # CoreDNS for custom DNS records
  coredns:
    image: coredns/coredns
    command: -conf /data/Main
    ports:
      - 53:53/udp
    volumes:
      - ./coredns/config:/data

    restart: unless-stopped

    networks:
      - home

  # Traefik for exposing web services
  reverse-proxy:
    image: traefik:v2.2
    command: --api.insecure=true --providers.docker
    ports:
      - "10.25.0.15:80:80"
      - "10.25.0.15:8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

    networks:
      - home

  # Gitea for local git storage
  # Plex

networks:
  home:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
